### ISSUE TITLE
Review +Inf and NaN JSON serialization

### ISSUE THREAD

**Issue by palmerabollo** [Telefonica/prometheus-kafka-adapter#12]
see https://github.com/prometheus/docs/pull/1197#issuecomment-431059439

**Comment by miguel-angel-monjas** [comment]
I'm getting some errors in the log in the following way:
`{"error":"json: unsupported value: NaN","level":"error","msg":"couldn't proccess timeseries","time":"2019-02-05T14:34:16Z"}
`
I assume that error is related to this issue, but it would be helpful to add the metrics name so that it is possible to trace it. Thanks

**Comment by palmerabollo** [comment]
Thanks @miguel-angel-monjas , we'll look into it. Can you confirm what version you are using?

**Comment by miguel-angel-monjas** [comment]
I'm using the Docker version. I assume it's 1.1.0:
`  prometheus-kafka-adapter:
    image: telefonica/prometheus-kafka-adapter:1.1.0
`
However, I haven't modified the log level (default to `info`). I'm activating the `debug` option to see whether there are further details. Thanks for your prompt answer
