### ISSUE TITLE
Exported metrics all are zero

### ISSUE THREAD

**Issue by liuzhen** [Telefonica/prometheus-kafka-adapter#41]
Hi, I was hoping to get the counter metrics of "metrics points sent to kafka", but all I got are:
* http_request counter
* queue size
and they are all 0.

Is this feature broken or working as designed?

**Comment by palmerabollo** [comment]
Hi @liuzhen. I'm not sure if I understand your question. You'll get the metrics you configure in your prometheus' remote_write section. Are those metrics (i.e. metrics points sent to kafka) available in your prometheus? In that case, you should see them in Kafka as well.

**Comment by jpfe-tid** [comment]
`http_requests_total` should increment on each **sucessful** remote write request received by the adapter.

https://github.com/Telefonica/prometheus-kafka-adapter/blob/d430b12d27810ecee67d5eaf6f87f6693c1eac60/handlers.go#L34

After a review of git history, `queueSize` was never implemented, probably because an internal queue was deprecated before open sourcing the adapter, therefore it is a leftover.

**Comment by jpfe-tid** [comment]
@liuzhen if you see `http_requests_total` equal to zero, could you share the version and enviromnent used so we can try to reproduce it?

**Comment by liuzhen** [comment]
Thanks.
We tested with more instances, and `http_requests_total` works now.
