### ISSUE TITLE
JSON marshalling - design question

### ISSUE THREAD

**Issue by davidmarkstartapp** [Telefonica/prometheus-kafka-adapter#5]
Hi

This repo looks very promising! thanks for that.

I'd like to ask design question, what stands behind the json marshalling instead of sending to kafka with prometheus format?

Also, how you implemented that opposite way kafka -> prometheus?

Thanks
D.

**Comment by javierprovecho** [comment]
Hi @davidmarkstartapp,

`kafka -> prometheus` is neither implemented or designed, but definitely something we should support in the future.

Right now, this is the open source version for dumping Prometheus metrics into Kafka.

We use JSON because data flows through Kafka to an Object Storage service where it is being archived for later querying to get KPIs, but we could easily support protobuf.

Our current output is a flexible schema with two fixed keys:

```json
{
  "__timestamp": 1234567890,
  "__value": 9876543210,
  
  "label1": "value1",
  "label2": "value2"
}
```

I'll add this example to the README tomorrow.

Thanks for your interest 👍 .

**Comment by palmerabollo** [comment]
@javierprovecho there could be a bug in the JSON serialization. I've added this issue https://github.com/Telefonica/prometheus-kafka-adapter/issues/2.

I'd say that kafka -> prometheus is a very low priority feature but we are open to contributions in this regard.

**Comment by davidmarkstartapp** [comment]
Thanks!
I'll take a look
Cool work guys!
